import { randomUUID } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  MAX_UPLOAD_BYTES,
  MAX_UPLOAD_MB,
  UPLOAD_MIME_EXTENSIONS,
} from "@/constants/upload";
import { ValidationError } from "@/lib/errors";
import type { UploadedFile } from "@/types/upload";

/**
 * Where uploaded files live.
 *
 * ## The driver
 *
 * Objects are written under `public/uploads`, which Next serves statically, so
 * an attachment URL is simply `/uploads/<key>`. This is the storage the project
 * asked for, and it needs no credentials and no new dependency — the Prisma
 * schema names Cloudinary and `folder-structure.md` names R2, but neither is
 * configured in `.env`.
 *
 * ## The seam
 *
 * Everything above this module talks to `storage.save()` / `storage.remove()`
 * and stores whatever `key` comes back. Moving to R2 or Cloudinary later means
 * reimplementing those two functions and backfilling existing keys — no route,
 * service or component changes.
 *
 * > **Deployment note:** a serverless host gives each invocation a fresh,
 * > usually read-only filesystem, so these files would not survive there. This
 * > driver is right for local development and for a single long-lived server.
 *
 * **Server-only.** It imports `node:fs`; a Client Component that needs the
 * upload limits imports `constants/upload.ts` instead.
 */

const UPLOAD_ROOT = path.join(process.cwd(), "public", "uploads");
const PUBLIC_PREFIX = "/uploads";

export const storage = {
  async save(file: File): Promise<UploadedFile> {
    if (file.size === 0) {
      throw new ValidationError("الملف فارغ");
    }

    if (file.size > MAX_UPLOAD_BYTES) {
      throw new ValidationError(
        `حجم الملف يتجاوز الحد المسموح (${MAX_UPLOAD_MB} ميجابايت)`,
      );
    }

    const extension = UPLOAD_MIME_EXTENSIONS[file.type];

    if (!extension) {
      throw new ValidationError("نوع الملف غير مدعوم");
    }

    // The stored name is generated, never taken from `file.name`: a filename
    // is attacker-controlled and would otherwise decide a path on disk.
    const key = `${randomUUID()}.${extension}`;
    const buffer = Buffer.from(await file.arrayBuffer());

    await mkdir(UPLOAD_ROOT, { recursive: true });
    await writeFile(path.join(UPLOAD_ROOT, key), buffer);

    return {
      key,
      url: `${PUBLIC_PREFIX}/${key}`,
      // Kept for display only — the original name is what an admin recognises
      // in a list, and it never touches the filesystem.
      name: file.name,
      size: file.size,
      contentType: file.type,
    };
  },

  /**
   * Best-effort delete. A missing object is not an error: the database row is
   * the record that matters, and refusing to delete it because its file is
   * already gone would strand the row forever.
   */
  async remove(key: string | null | undefined): Promise<void> {
    if (!key) return;

    const target = path.resolve(UPLOAD_ROOT, key);

    // Defence in depth. Keys are generated by `save`, but a stored key is
    // still data — and data must never be able to point outside the root.
    if (!target.startsWith(UPLOAD_ROOT + path.sep)) return;

    try {
      await unlink(target);
    } catch {
      // Already gone, or never written by this driver.
    }
  },
};
